from django.urls import path,include
from . import views
from job.views import*
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('', views.index,name='index'),
    path('job', views.job,name='job'),
    path('search', views.search, name='search'),
    path('search1', views.search1, name='search1'),
    path('search2', views.search2, name='search2'),
    path('videosearch', views.videosearch, name='videosearch'),
    path('vacancysearch', views.vacancysearch, name='vacancysearch'),
    path('resumesearch', views.resumesearch, name='resumesearch'),
    path('todaysearch', views.todaysearch, name='todaysearch'),
    path('yesterdaysearch', views.yesterdaysearch, name='yesterdaysearch'),
    path('myvideo', views.myvideo, name='myvideo'),
    path('login', views.login,name='login'),
    path('recruiterlogin', views.recruiterlogin,name='recruiterlogin'),
    path('logout', views.Logout, name='Logout'),
    path('usersignup', views.usersignup,name='usersignup'),
    path('recruitersignup', views.recruitersignup, name='recruitersignup'),
    path('adminlogin', views.adminlogin,name='adminlogin'),
    path('changepassword', views.changepassword, name='changepassword'),
    path('changepasswordforrecruiter', views.changepasswordforrecruiter, name='changepasswordforrecruiter'),
    path('bosspage', views.bosspage, name='bosspage'),
    path('latestjob', views.latestjob, name='latestjob'),
    path('latestjobpageforrecruiter', views.latestjobpageforrecruiter, name='latestjobpageforrecruiter'),
    path('recruitermainpage', views.recruitermainpage, name='recruitermainpage'),
    path('delete_user/<int:pid>', views.delete_user, name='delete_user'),
    path('delete_recruiter/<int:pid>', views.delete_recruiter, name='delete_recruiter'),
    path('delete_post/<int:pid>', views.delete_post, name='delete_post'),
    path('delete_postbyadmin/<int:pid>', views.delete_postbyadmin, name='delete_postbyadmin'),
    path('delete_apply/<int:pid>', views.delete_apply, name='delete_apply'),
    path('updatepost/<int:pid>', views.updatepost, name='updatepost'),
    path('delete_resume', views.delete_resume, name='delete_resume'),
    path('userdata', views.userdata,name='userdata'),
    path('recruiterdata', views.recruiterdata,name='recruiterdata'),
    path('addjob', views.addjob,name='addjob'),
    path('userprofileupdate', views.userprofileupdate,name='userprofileupdate'),
    path('userstatusbar', views.userstatusbar, name='userstatusbar'),
    path('recruiterstatusbar/', views.recruiterstatusbar, name='recruiterstatusbar'),
    path('recruiterprofileupdate', views.recruiterprofileupdate, name='recruiterprofileupdate'),
    path('detail/<int:pid>', views.detail,name='detail'),
    path('detailforrecruiter/<int:pid>', views.detailforrecruiter, name='detailforrecruiter'),
    path('singlestatus/<int:pid>', views.singlestatus, name='singlestatus'),
    path('statuschange/<int:pid>', views.statuschange, name='statuschange'),
    path('statusfieldkadata/<int:pid>', views.statusfieldkadata, name='statusfieldkadata'),
    path('video', views.video,name='video'),
    path('addresume', views.addresume,name='addresume'),
    path('countofappliedstudent', views.countofappliedstudent,name='countofappliedstudent'),
    path("password-reset/", auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name="password_reset"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"), name='password_reset_confirm'),
    path("password_reset_complete", auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name="password_reset_complete"),
    path('aboutus', views.aboutus, name='aboutus'),
    path('placedstudent', views.placedstudent, name='placedstudent'),
    path('postofeveryrecruiter/<int:pid>', views.postofeveryrecruiter, name='postofeveryrecruiter'),
    path('interviewquestion/', views.interviewquestion, name='interviewquestion'),
    path('feedback/', views.feedback, name='feedback'),
    path('deletefeedback/<int:pid>', views.deletefeedback, name='deletefeedback'),
    path('bestyoutubechannel', views.bestyoutubechannel, name='bestyoutubechannel'),
    path('grandmaa', views.grandmaa, name='grandmaa'),
    path('chat/', views.chat, name='chat'),
    path('chat/<int:sender>/<int:receiver>/', views.message_view, name='chat'),
    path('api/messages/<int:sender>/<int:receiver>/', views.message_list, name='message-detail'),
    path('api/messages/', views.message_list, name='message-list'),
    path('videocalling', views.videocalling, name='videocalling'),

              ]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
