# Generated by Django 3.2.6 on 2021-08-13 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('content', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100, null=True)),
                ('video', models.FileField(null=True, upload_to='')),
                ('thumbnail', models.FileField(null=True, upload_to='')),
                ('type', models.CharField(max_length=100, null=True)),
                ('creationdate', models.DateField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('gender', models.CharField(max_length=10, null=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('resume', models.FileField(null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('gender', models.CharField(max_length=10, null=True)),
                ('company', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('salary', models.CharField(max_length=10, null=True)),
                ('permonth', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('experience', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=15)),
                ('skill', models.CharField(max_length=300, null=True)),
                ('creationdate', models.DateField()),
                ('company', models.CharField(max_length=50)),
                ('paid', models.CharField(blank=True, max_length=10, null=True)),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='')),
                ('applied_date', models.DateField(null=True)),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('interviewdateaandtime', models.DateTimeField(blank=True, null=True)),
                ('joiningletter', models.FileField(blank=True, null=True, upload_to='')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.studentuser')),
            ],
        ),
    ]
